// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type GenerateVariantsInput struct {
	Variants []*Variant `json:"variants"`
}

type GenerateVariantsPayload struct {
	Sku            string    `json:"sku"`
	VariantTitle   []*string `json:"variantTitle"`
	VariantOptions []*string `json:"variantOptions"`
	FactoryPrice   float64   `json:"factoryPrice"`
	ShopPrice      float64   `json:"shopPrice"`
	CustomerPrice  float64   `json:"customerPrice"`
	Quantity       int       `json:"quantity"`
	FileKey        string    `json:"fileKey"`
}

type Variant struct {
	Title   string   `json:"title"`
	Options []string `json:"options"`
}
